### PR TITLE
fix: normalize `process.cwd` on windows

### LINKED ISSUE #30: Inconsistant `path.relative` result
```js
import * as pathPosix from 'node:path/posix';
import * as pathWin32 from 'node:path/win32';
import * as pathe from 'pathe';
import * as pathe02 from 'pathe0.2';

const a = process.cwd().replaceAll('\\', '/');
const b = './dist/client/b-scroll.d.ts';

console.log('node:path/posix', pathPosix.relative(a, b));
console.log('node:path/win32', pathWin32.relative(a, b));
console.log('pathe 0.3.2', pathe.relative(a, b));
console.log('pathe 0.2.0', pathe02.relative(a, b));
```
https://stackblitz.com/edit/node-rdaxjo?file=index.js

Running this on stackblitz outputs
```
node:path/posix dist/client/b-scroll.d.ts
node:path/win32 dist\client\b-scroll.d.ts
pathe 0.3.2 dist/client/b-scroll.d.ts
pathe 0.2.0 dist/client/b-scroll.d.ts
```

Running this on Windows outputs (pwd is `C:\Users\green\Downloads\node-rdaxjo`)
```
node:path/posix ../../../../../dist/client/b-scroll.d.ts
node:path/win32 dist\client\b-scroll.d.ts
pathe 0.3.2 ../../../../../C:\Users\green\Downloads\node-rdaxjo/dist/client/b-scroll.d.ts
pathe 0.2.0 ../../../../../dist/client/b-scroll.d.ts
```

I expect pathe to return `dist/client/b-scroll.d.ts`.

### PR DESCRIPTION
**Pull request by danielroe**
resolves #30

### CODE REVIEW

File: src/path.ts [hunk 1]
```diff
@@ -82,7 +82,7 @@ export const resolve: typeof path.resolve = function (...args) {
   let resolvedAbsolute = false
 
   for (let i = args.length - 1; i >= -1 && !resolvedAbsolute; i--) {
-    const path = i >= 0 ? args[i] : process.cwd()
+    const path = i >= 0 ? args[i] : normalize(process.cwd())
```
Comment (pi0) [inline src/path.ts:85]: Can it be a lighter operation for slash normalization?

**Review by pi0 — APPROVED** [review]
Thanks!
